### PR TITLE
add support for RGB hex colours

### PR DESCRIPTION
**Pull request by hugowetterberg**

### CODE REVIEW

**Review by dannelundqvist — CHANGES_REQUESTED** [review]
I think it would be a good idea to support color the two definitions rgb and rgba (e.g. _rgb(127, 127, 127,)_ and _rgba(127, 127, 127, 0.5)_) to accomodate for different design systems. More and more they are used over hex codes.

**Comment by hugowetterberg** [comment]
Fair, but I'll limit it to the `rgba(255,255,255,1.0)` notation, apparently it's possible to use `rgba(100%,100%,100%,1.0)` .

**Comment by hugowetterberg** [comment]
During the morning walk I realised that I don't like having the different colour types being top level formats (and mutually exclusive). I'll take another stab at this.

**Comment by hugowetterberg** [comment]
There's now a `colourFormats` directive that makes it possible to specify the accepted formats. This makes it possible to accept multiple formats, and it will also be easier to add new colours (like `hsl()`) in the future.

**Review by dannelundqvist — APPROVED** [review]

**Pull request merged**
